document.writeln("<script type=\'text/javascript\' id=\'MathJax-script\' async");
document.writeln("    src=\'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js\'>");
document.writeln("</script>");
document.writeln("<script>");
document.writeln("MathJax = {");
document.writeln("    tex: {");
document.writeln("        inlineMath: [[\'$\', \'$\']]");
document.writeln("    }");
document.writeln("};");
document.writeln("</script>");
document.writeln("<script id=\'MathJax-script\' async");
document.writeln("    src=\'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js\'>");
document.writeln("</script>");
document.writeln("");
document.writeln("<table>");
document.writeln("    <head>");
document.writeln("        <tr>");
document.writeln("            <th width=\'196\'>网站导航</th>");
document.writeln("            <th width=\'196\'><a href=\'https://www.dywan.xyz\'>个人主页</a></th>");
document.writeln("            <th width=\'196\'><a href=\'https://www.dywan.xyz/blog\'>博客首页</a></th>");
document.writeln("            <th width=\'196\'><a href=\'https://www.dywan.xyz/note\'>笔记首页</a></th>");
document.writeln("            <th width=\'196\'><a href=\'https://github.com/wdygh1997\'>GitHub主页</a></th>");
document.writeln("        </tr>");
document.writeln("    </head>");
document.writeln("</table>");
